version: '2.1'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g -XX:MaxMetaspaceSize=256m"
      ELASTIC_PASSWORD: changeme
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:changeme", "http://elasticsearch:9200/_cat/health?h=status"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m -XX:MaxMetaspaceSize=256m"
    restart: always
    networks:
      - elk
    depends_on:
      elasticsearch:
          condition: service_healthy

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://kibana:5601/status"]
      retries: 6
    depends_on:
      elasticsearch:
          condition: service_healthy

  filebeat:
    build:
      context: filebeat/
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml:ro
      - ./filebeat/prospectors.d:/usr/share/filebeat/prospectors.d
      - /var/log:/etc/logs:ro
    networks:
      - elk
    restart: always
    depends_on:
      kibana:
          condition: service_healthy

  metricbeat:
    build:
      context: metricbeat/
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/config/metricbeat.yml:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    networks:
      - elk
    restart: always
    depends_on:
      elasticsearch:
          condition: service_healthy


volumes:
  elasticsearch_data:
    driver: rexray/ebs:latest
    driver_opts:
      size: 500
      volumeType : gp2

networks:

  elk:
    driver: bridge
