- type: log
  ignore_older: 1h
  paths:
    - /etc/logs/*/log/community*.log
    - /etc/logs/*/log/methode*.log
    - /etc/logs/*/log/epaper*.log
    - /etc/logs/*/log/xml_import*.log
    - /etc/logs/*/log/eventLogger*.log
    - /etc/logs/*/log/startup*.log
  scan_frequency: 5
  fields_under_root: true
  fields:
    type: services-log
  ## 2018-03-15 16:06:00,023  INFO
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after


